//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesionCliente
    {
        public int idProfesion_Cliente { get; set; }
        public Nullable<int> idProfesion { get; set; }
        public Nullable<int> idCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Profesion Profesion { get; set; }
    }
}
